bro_log_dir: '/opt/bro/logs/'

mailing_list:
  - 'n.siow@wustl.edu'
  - 'compilewithstyle@gmail.com'

max_alerts: 50

throttle_db: "/Users/nsiow/box/code/work_projects/blackbook/bookie/dat/throttle.sqlite"
